### ISSUE TITLE
Plugin create .rebar3 folder in test dir

### ISSUE THREAD

**Issue by hiend** [ferd/rebar3_proper#15] opened 2017-05-30 12:11 UTC
After each run `rebar3 proper -v`

$ cd ./apps/myapp/test/.rebar3 ; ls -la
-rw-rw-r-- 1 hiend hiend  444 may 30 16:04 erlcinfo

is this the right behavior?

**Comment by NobbZ** [comment] 2017-05-30 12:17
The proper plugin does not create anything in the filesystem on its own.

Therefore, please check if this directory and file is created as well when you run `rebar3 compile`. `rebar3` makes sure that `compile` is run and current before even handing over to this plugin.

If it is not created when running `rebar3 compile`, it still might get created by `proper`, but due to the name I doubt that.

Also please provide your exact version of rebar and the rebar3_proper plugin used.

**Comment by hiend** [comment] 2017-05-30 13:28
I checked before posting (`compile`, `as test compile`, etc), it only happens when the `rebar3 proper` was used.

rebar 3.4.1 on Erlang/OTP 19 Erts 8.3
rebar3_proper 0.7.2

**Comment by ferd** [comment] 2017-05-30 20:52
Rebar3 proper does *not* create any files other than a counterexample file: https://github.com/ferd/rebar3_proper/blob/master/src/rebar3_proper_prv.erl#L172-L180

Moreoever that file should be stored in `_build/test`. The .erlcinfo file, though, appears to be created by the compiler util in rebar3 itself: https://github.com/erlang/rebar3/blob/54cb748cac69f7aac296d9e8c177d7761ebcd510/src/rebar_erlc_compiler.erl 

The file is created in the local cache directory: https://github.com/erlang/rebar3/blob/54cb748cac69f7aac296d9e8c177d7761ebcd510/src/rebar_erlc_compiler.erl#L376-L377

I'm not quite sure where it ends up where it is, maybe @talentdeficit would since he rewrote a lot of the compiler util, but the problem is seemingly not with the plugin itself. I'm not sure why the plugin is alone to trigger it though.

**Comment by ehamberg** [comment] 2019-03-09 17:48
I'm seeing the same issue with a `erlcinfo` file being generated in apps' test directories under a `.rebar3/` directory. I also only see it when using `rebar3 proper`.

I also get the following error when I run `rebar3 proper` – not sure if it's related:

    ===> Calling deprecated rebar_erlc_compiler compiler module. This module has been replaced by rebar_compiler and rebar_compiler_erl, but will remain available.

**Comment by ferd** [comment] 2019-03-10 14:21
Yeah that's pretty much guaranteed to be the problem. The old compiler stores metadata there. I don't know when I'll tackle the issue.

**Comment by ferd** [comment] 2020-07-05 02:47
Should be fixed as of 0.12.0

**Closed as completed by ferd** 2020-07-05 02:47 UTC
